apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-server
  labels:
    app: nodejs-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs-server
  template:
    metadata:
      labels:
        app: nodejs-server
    spec:
      containers:
      - name: nodejs-server
        image: 684694267050.dkr.ecr.us-east-1.amazonaws.com/node-server:22307d0222f15078606627b9d952ed2c2947a070 # Update this to use a specific tag
        ports:
        - containerPort: 3001
        env:
        - name: NODE_ENV
          value: "production"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
